### ISSUE TITLE
Using &newWindow when atom isn't already open, opens up a blank new window, and then the link in another new window

### ISSUE THREAD

**Issue by CyborgSemon** [UziTech/atom-open#2]
Exactly what the title says.
Not exactly a huge issue, but slightly annoying.

Atom version: 1.36.0
Open version: 0.1.1
MacOS version: 10.14.4

**Comment by UziTech** [comment]
This should be fixed in v1.3

**Comment by CyborgSemon** [comment]
I still seems to be happening. If atom already has a window open, then it opens fine. But if the app is closed, or there are no current windows open, then it still opens up 2 windows. One with a brand new untitled document, then the second one with the file / folder location open.

**Comment by UziTech** [comment]
sorry had a bug in the check for a new window

**Comment by CyborgSemon** [comment]
Sweet it works great now!
Thanks!
