### ISSUE TITLE
Latest atom update has stoped this package from working

### ISSUE THREAD

**Issue by CyborgSemon** [UziTech/atom-open#5]
Atom just updated, and now I cant seem to get any of this packages features to work.
Current atom version: 1.36.1
Current MacOS version: 10.14.4

**Comment by UziTech** [comment]
Can you provide a link that isn't working?

**Comment by UziTech** [comment]
looks like the issue is https://github.com/atom/atom/commit/952c42c0de8cdab2661856f5dd4789a1d69e08ee changed the name of a setting

**Comment by UziTech** [comment]
This is fixed in v2.0.2

**Comment by CyborgSemon** [comment]
Works great now thanks!
